# This is a basic workflow to help you get started with Actions

name: create

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python  # 安装python环境 
        uses: actions/setup-python@v2
        
      - name: Install Python dependencies  # 安装python爬虫依赖包
        run: python -m pip install urllib3 lxml

      - name: Run python   # 生成新的README.md文件 
        run: python generateReadme.py

      - name: Record time  
        run: echo `date` > date.log

      - name: Commit and push if changed   # 将README.md更新到仓库
        run: |
          git diff
          git config --global user.email "641474670@qq.com"
          git config --global user.name "BYChoo"
          git add -A
          git commit -m "Updated Readme" || exit 
          git push
